### ISSUE TITLE
cross-compile for Elk Pi RPi3B

### ISSUE THREAD

**Issue by Nickgonzales76017** [elk-audio/elkpi-sdk#5]
I am using the raspberry pi 3b with the hifi berry ADC +DAC  converter. I am trying to cross compile a VST to run with sushi, but I keep receiving this error and am un sure how to proceed.  I believe that I am having an issue extracting the sdk to compile the linux maker file from juce 6.
![proof](https://user-images.githubusercontent.com/45552585/142749741-e3aa4707-1d87-4df2-9e3c-bbe73ab78488.PNG)
.

**Comment by IliasBergstrom** [comment]
Hi!
If you are building directly on the RPi3 board, you do not need to x-compile. You can just build natively, assuming you have a "dev" image of the Elk Audio OS, and all necessary libraries available. That is however best avoided, especially on the slower RPi3.

That is why we provide the x-compilation toolchain, so that you can create binaries for the RPi, on your normal (e.g. Ubuntu) Linux computer.

I will go ahead and close this issue, since it is not a problem with the SDK. 

But do feel free to ask us any further questions you have on our forum: https://forum.elk.audio/

Edit: Just in case, I take the chance to point you to [our documentation](https://elk-audio.github.io/elk-docs/html/index.html) - it is quite extensive and should get you quite far along the way, though for sure the forum is likely to come in handy in the process too.

Best,
Ilias B.

**Comment by Nickgonzales76017** [comment]
Thank you for the fast reply.
I got the toolchain to extract using ubuntu wsl on windows and brought the LinuxMakefile, Source file, and JuceLibraryfiles from windows to the ubuntu wsl enviorment,. Now I am receiving this error and am un sure how to proceed.

![proof](https://user-images.githubusercontent.com/45552585/142897578-242850fb-5d77-4e0c-a906-de6232cbbc12.PNG)
ps. also asked on https://forum.elk.audio/t/elk-audio-rpi3-toolchain/729

**Comment by Nickgonzales76017** [comment]
It turns out the above error was due to some mislinked JUCE modules folders. 
Now I am getting this error.
![proof](https://user-images.githubusercontent.com/45552585/142947568-909680d0-cdad-4138-a82f-b20e230315d8.PNG)

**Comment by IliasBergstrom** [comment]
Hi! I'll reply on the forum post you linked.
